name: run-react-tests
run-name: ${{ github.actor }} is running React tests
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      -
        name: Build test container
        uses: docker/build-push-action@v4
        with:
          context: ./client
          load: true
          file: ./client/Dockerfile.dev
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-test:latest
      -
        name: Run tests
        run: |
          docker run --rm -e CI=true ${{ secrets.DOCKERHUB_USERNAME }}/react-test npm test
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-client
      -
        name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-nginx
      -
        name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-server
      -
        name: Build and push worker image
        uses: docker/build-push-action@v4
        with:
          context: ./worker
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker
        
  
